"""create table movie

Revision ID: 19d08e81963f
Revises: d8d7ebf499c8
Create Date: 2018-07-01 17:37:34.526726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d08e81963f'
down_revision = 'd8d7ebf499c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
