"""create tables

Revision ID: 1ebbbd90b77e
Revises: 6eb3c6415cee
Create Date: 2018-06-30 17:23:54.035844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ebbbd90b77e'
down_revision = '6eb3c6415cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
