"""create tables

Revision ID: 6eb3c6415cee
Revises: ea52e5186f1d
Create Date: 2018-06-30 17:22:45.321389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb3c6415cee'
down_revision = 'ea52e5186f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
