"""create table img 

Revision ID: 7cb3cdb4d9cd
Revises: 55223a50b457
Create Date: 2018-06-30 17:14:33.020267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb3cdb4d9cd'
down_revision = '55223a50b457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
