"""updata table

Revision ID: dbdfee2433bf
Revises: e68235975dfe
Create Date: 2018-07-03 20:42:50.838617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbdfee2433bf'
down_revision = 'e68235975dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('actor', sa.String(), nullable=True))
    op.add_column('movie', sa.Column('logintime', sa.String(), nullable=True))
    op.add_column('movie', sa.Column('movie_type', sa.String(), nullable=True))
    op.add_column('movie', sa.Column('time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'time')
    op.drop_column('movie', 'movie_type')
    op.drop_column('movie', 'logintime')
    op.drop_column('movie', 'actor')
    # ### end Alembic commands ###
