"""create table img 

Revision ID: ea52e5186f1d
Revises: 7cb3cdb4d9cd
Create Date: 2018-06-30 17:19:54.436648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea52e5186f1d'
down_revision = '7cb3cdb4d9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
